title: Eine Einführung in REST
author: Peter Braun
email:  mail@peter-braun.org
description: Umfassende Einführung in die Programmierung von REST Servern

url:              'https://braupet.github.io'
baseurl:          '/restbook'
rss:              RSS

remote_theme: sighingnow/jekyll-gitbook

syntax_highlighter_style: colorful

toc:
    enabled: true
    h_min: 1
    h_max: 3
    
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true
 
 markdown_ext:     markdown,mkdown,mkdn,mkd,md
 
 collections:
  pages:
    output: true
    permalink: /:collection/:path/
    
 page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true
